# Generated by Django 3.1.7 on 2021-03-28 08:25

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='members.user')),
                ('student_code', models.CharField(max_length=14)),
                ('incoming_semester', models.CharField(max_length=3)),
                ('grade', models.CharField(choices=[('AS', 'Associate'), ('BC', 'Bachelor'), ('MS', 'Master'), ('DR', 'Doctorate')], max_length=2)),
                ('status', models.CharField(choices=[('ST', 'Studying'), ('AS', 'Graduated'), ('BC', 'Fired')], max_length=2)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('members.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
